FROM python:3.11-slim

WORKDIR /app

# requirements.txt 복사
COPY backend/requirements.txt .

# 패키지 설치
RUN pip install --no-cache-dir -r requirements.txt

# 서버 코드 복사
COPY backend/ . 

EXPOSE 5000

CMD ["python", "app.py"]
